import lombok.Getter;
import lombok.Setter;
import java.util.Map;

/**
 * The type AnswerObject.
 * <p>
 * It contains the relevant information for an answer generated by a language model. Note that it belongs to a
 * question. The question is not present here since one question can have multiple answers (generated by different
 * language models). An {@link AnswerObject} should be stored together with its respective question (e.g. within a
 * {@link Map}).
 *
 * @see QAObject#qaPairs
 */
public class AnswerObject {

    /**
     * The answer of a question
     */
    @Getter
    @Setter
    private String answer;

    /**
     * The name of the language model that generates {@link #answer}
     */
    @Getter
    @Setter
    private String modelName;

    /**
     * The initial position of the found answer in the given corpus
     *
     * @see QAObject#corpus
     * @see QAObject#CORPUS_FILE
     */
    @Getter
    @Setter
    private int beginPosition;

    /**
     * The final position of the found answer in the given corpus
     *
     * @see QAObject#corpus
     * @see QAObject#CORPUS_FILE
     */
    @Getter
    @Setter
    private int endPosition;

    /**
     * Instantiates a new AnswerObject.
     *
     * @param answer        the answer
     * @param modelName     the model name
     * @param beginPosition the begin position
     * @param endPosition   the end position
     */
    public AnswerObject(String answer, String modelName, int beginPosition, int endPosition) {
        this.answer = answer;
        this.modelName = modelName;
        this.beginPosition = beginPosition;
        this.endPosition = endPosition;
    }
}
